version: "3.9"

services:
  trust-api:
    build: ./backend
    ports:
      - "8080:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - trust-api
